# Generated by Django 4.0.4 on 2022-05-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0004_video_dislikes_video_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='dislikes',
        ),
    ]
