# Generated by Django 4.0.4 on 2022-05-09 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0006_alter_video_options_video_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='tags',
            new_name='tag',
        ),
    ]
