# Generated by Django 4.0.4 on 2022-05-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0009_alter_video_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tag',
            field=models.CharField(choices=[('1', 'asmr'), ('2', 'gaming'), ('3', 'vlog'), ('4', 'music'), ('5', 'animation')], max_length=100, null=True),
        ),
    ]
