# Generated by Django 4.0.4 on 2022-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0010_alter_video_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
