# Generated by Django 4.0.4 on 2022-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlog', '0004_video_dislikes_video_likes_comment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_videos',
            field=models.ManyToManyField(to='vlog.video'),
        ),
    ]
